site_name: Darwin.Net Documentation
site_description: Documentation site for Darwin.Net

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Reference:
    - API Reference: reference/api.md
    - Configuration Reference: reference/config.md

theme:
  name: cosmo

plugins:
  - search
  - toc