name: Build and Test Darwin.Net

on:
  push:
    paths-ignore:
      - "docs/**"
      - ".gitassets/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create app.config file
      run: echo '<?xml version="1.0" encoding="utf-8" ?>
        <configuration>
            <appSettings>
                <add key="DarwinApiKey" value="${{ secrets.DARWINDEVKEY }}" />
            </appSettings>
        </configuration>' > DarwinTests/app.config
      env:
        MY_SECRET: ${{ secrets.DARWINDEVKEY }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x' # or the version you need

    - name: Build project
      run: dotnet build Darwin.Net.sln --configuration Release

    - name: Run test cases
      run: dotnet test Darwin.Net.sln --configuration Release
