name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: refs/heads/Release-${{ github.event.release.tag_name }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack DarwinNet/DarwinNet.csproj --configuration Release --include-symbols

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGETKEY }}

      - name: Push to NuGet
        run: dotnet nuget push ./DarwinNet/bin/Release/*.nupkg --skip-duplicate -k ${{ secrets.NUGETKEY }} -s https://api.nuget.org/v3/index.json

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Merge Release-${{ github.event.release.tag_name }} into master"
          commit-message: "Merge Release-${{ github.event.release.tag_name }} into master"
          branch: master
          base: release-${{ github.event.release.tag_name }}
          body: |
            - Include release artifacts:
              - DarwinNet/bin/Release/*.nupkg
              - DarwinNet/bin/Release/*.dll
          token: ${{ secrets.PAT }}

      - name: Add release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ github.event.release.tag_name }}-artifacts
          path: |
            DarwinNet/bin/Release/*.nupkg
            DarwinNet/bin/Release/*.dll
