name: Publish to NuGet

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack DarwinNet/DarwinNet.csproj --configuration Release --include-symbols
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
        with:
          nuget-api-key: ${{ secrets.NUGETKEY }}
          
      - name: Publish to NuGet
        run: dotnet nuget push ./DarwinNet/bin/Release/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
