name: Update Documentation

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0

    - name: Install DocFX
      run: dotnet tool install --global docfx
      
    - name: List directory contents
      run: |
        ls -R ../

    - name: Build documentation
      run: |
        export PATH="$HOME/.dotnet/tools:$PATH"
        docfx docs/docfx.json --output out
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: out
        token: ${{ secrets.PAT }}
